apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "employee" # Name of the database
            - name: POSTGRES_USER
              value: "postgres" # Username for PostgreSQL
            - name: POSTGRES_PASSWORD
              value: "shubham2003" # Password for PostgreSQL
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {} # For persistent storage, use a PersistentVolumeClaim
